// demo-react-tiger-admin/src/layouts/Header/index.tsx
import React, { FC, useEffect } from 'react';
import { Avatar, Layout, Menu, Dropdown } from 'antd';
import { Link, useHistory } from 'react-router-dom';
import FullScreen from '@/components/FullScreen';
import Hamburger from '@/components/Hamburger';
import headImg from '@assets/default-head-02.png';
import BreadCrumb from '@/components/BreadCrumb';
import { useStore } from '@/store';
import { useStorage } from '@/hooks/common';
import { Gitee } from '@/common/constants';

const { Header } = Layout

type Props = {
  token?: string
}

const Item = Menu.Item;

// 头部组件
const AppHeader: FC<Props> = () => {
  const history = useHistory();
  const { userStore } = useStore()
  const storage = useStorage();
  const { nickname } = storage.get({path: 'info'});

  const toLogin = () => {
    history.push('/login');
  }

  useEffect(() => {
    if (!nickname) {
      toLogin();
    }
  }, [nickname])

  const onDropMenu = (e: any) => {
    if (e.key === 'uppassword') {
      console.log('up');
    }
    if (e.key === 'logout') {
      userStore.logout();
      toLogin();
    }
  }

  // 下拉菜单组件
  const dropMenu = (
    <Menu className="app-overlay-menu" onClick={onDropMenu}>
      <Item key="index" style={{display: 'none'}}>
        <Link to="/">首页</Link>
      </Item>
      <Item key="gitee">
        <a href={Gitee} target="_blank" rel="noopener noreferrer">项目地址</a>
      </Item>
      <Item key="uppassword" style={{display: 'none'}}>
        修改密码
      </Item>
      <Menu.Divider/>
      <Item key="loggout">登出</Item>
    </Menu>
  );

  return (
    <Header className="app-header">
      <Hamburger/>
      <BreadCrumb/>
      <div className="app-helper-menu">
        <FullScreen/>
        <div className="header-dropdown-wrap">
          <Dropdown overlayClassName="app-header-down" arrow overlay={dropMenu} overlayStyle={{ right: '-30px', left: 0}}>
            <div>
              <Avatar size={32} src={headImg} />
              <span className="app-name">{nickname}</span>
            </div>
          </Dropdown>
        </div>
      </div>
    </Header>
  );
}

export default AppHeader;

// demo-vue-tiger-admin/src/layouts/Header/index.vue
<script setup lang="ts">
  import { Gitee } from '@/config/constants'
  import Hamburger from '@/components/Hamburger/index.vue'
  import FullScreen from '@/components/FullScreen/index.vue'
  import BreadCrumb from '@/components/BreadCrumb/index.vue'
  import useUserStore from '@/store/modules/user'
  import { useRouter } from 'vue-router'
  import { useAppStore } from '@/store'

  const userStore = useUserStore()
  const appStore = useAppStore()
  const router = useRouter()
  const nickname = 'admin'

  // 全局设置打开
  const setVisible = () => {
    appStore.updateSettings({ globalSettings: true })
  }

  // 登出
  const logout = async () => {
    await userStore.logout()
    router.push('/login')
  }
</script>

<template>
  <a-layout-header class="app-header">
    <!-- 汉堡组件和面包屑组件 -->
    <Hamburger />
    <BreadCrumb />
    
    <!-- 帮助菜单 -->
    <div class="app-helper-menu">
      <ul class="header-dropdown-wrap">
        <!-- 全屏 -->
        <li>
          <FullScreen />
        </li>

        <!-- 打开全局设置（设置变成可见） -->
        <li>
          <a-tooltip content="设置">
            <a-button class="nav-btn" type="outline" :shape="'circle'" @click="setVisible">
              <template #icon>
                <icon-settings />
              </template>
            </a-button>
          </a-tooltip>
        </li>

        <li>
          <a-dropdown class="app-overlay-menu" trigger="hover">
            <div>
              <img class="app-header-avatar" alt="avatar" src="@/assets/default-head-02.png" />
              <span className="app-name">{{ nickname }}</span>
            </div>
            <template #content>
              <a-doption>
                <a-space>
                  <icon-home />
                  <a-link @click="$router.push({ name: 'dashboard' })">首页</a-link>
                </a-space>
              </a-doption>
              <a-doption>
                <a-space>
                  <icon-github />
                  <a-link :href="Gitee" target="_blank" rel="noopener noreferrer">项目地址</a-link>
                </a-space>
              </a-doption>
              <a-divider />
              <a-doption @click="logout">
                <a-space>
                  <icon-export />
                  <span>登出</span>
                </a-space>
              </a-doption>
            </template>
          </a-dropdown>
        </li>
      </ul>
    </div>
  </a-layout-header>
</template>
